version = 1

test_patterns = ["/spec/**"]

exclude_patterns = [
    "/docs/**",
    "/git-hooks/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "6"
  module_system = "es-modules"
  environment = [
    "nodejs",
    "browser"
  ]
  dialect = "typescript"